### ISSUE TITLE
Prometheus endpoint?

### ISSUE THREAD

**Issue by jkroepke** [prodzilla/prodzilla#4]
Do you plan to add a prometheus endpoint? For most things, blackbox_exporter is good, but the stories feature of produia is insane.

Also I like the async interval monitoring. At the moment, we are limited to 4min maximim interval.

**Comment by codingupastorm** [comment]
Hey @jkroepke, appreciate the feedback - a prometheus endpoint makes sense and will definitely add one if there's demand. Consider it on the backlog - but after a couple of things like the "variables" feature of stories

**Comment by stevensdavid** [comment]
It probably wouldn't be too tricky to introduce Prometheus support now that we have OpenTelemetry metrics, there seems to be a [crate bridging the two](https://docs.rs/opentelemetry-prometheus/latest/opentelemetry_prometheus/) so all that should be necessary is switching the metrics exporter based on some configuration 🤔 If we stick to the OpenTelemetry specification then this should be select based on the environment variable `OTEL_METRICS_EXPORTER=prometheus` ([see specification](https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#exporter-selection)), I might take a look at this soon
